/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tuan3;

/**
 *
 * @author Yuumi
 */
public class lab2 extends javax.swing.JFrame {


    /**
     * Creates new form Demo
     */
    public lab2() {
        initComponents();
    }
    private long a = 0;
    private String phepToan="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton12 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        hienThi = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnchia = new javax.swing.JButton();
        btncanbac = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnnhan = new javax.swing.JButton();
        btnphantram = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btntru = new javax.swing.JButton();
        btnchiax = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btncongtru = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btncong = new javax.swing.JButton();
        btnbang = new javax.swing.JButton();

        jButton12.setText("jButton12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        hienThi.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        hienThi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hienThi.setText("0");
        hienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hienThiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hienThi, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hienThi, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new java.awt.GridLayout(4, 5));

        btn1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1);

        btn2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2);

        btn3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3);

        btnchia.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btnchia.setText("/");
        btnchia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchiaActionPerformed(evt);
            }
        });
        jPanel2.add(btnchia);

        btncanbac.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btncanbac.setText("sqrt");
        btncanbac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncanbacActionPerformed(evt);
            }
        });
        jPanel2.add(btncanbac);

        btn4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4);

        btn5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5);

        btn6.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6);

        btnnhan.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btnnhan.setText("*");
        btnnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhanActionPerformed(evt);
            }
        });
        jPanel2.add(btnnhan);

        btnphantram.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btnphantram.setText("%");
        btnphantram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphantramActionPerformed(evt);
            }
        });
        jPanel2.add(btnphantram);

        btn7.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7);

        btn8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8);

        btn9.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9);

        btntru.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btntru.setText("-");
        btntru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntruActionPerformed(evt);
            }
        });
        jPanel2.add(btntru);

        btnchiax.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btnchiax.setText("1/x");
        btnchiax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchiaxActionPerformed(evt);
            }
        });
        jPanel2.add(btnchiax);

        btn0.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn0);

        btncongtru.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btncongtru.setText("+/-");
        jPanel2.add(btncongtru);

        btndelete.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btndelete.setText("C");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btndelete);

        btncong.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btncong.setText("+");
        btncong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncongActionPerformed(evt);
            }
        });
        jPanel2.add(btncong);

        btnbang.setText("=");
        btnbang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbangActionPerformed(evt);
            }
        });
        jPanel2.add(btnbang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(647, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 357, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
      String gt=this.hienThi.getText();
      if (gt.length()<12){
          if (gt.equals("1")) gt="";
          long so = Long.parseLong(gt+ btn1.getText());
          this.hienThi.setText(String.valueOf(so));
          
          
      }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btnchiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchiaActionPerformed
      this.a = Long.parseLong(this.hienThi.getText());
      if (this.a !=0);
      this.phepToan = "/";
      this.hienThi.setText("0");
        
    }//GEN-LAST:event_btnchiaActionPerformed

    private void hienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hienThiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hienThiActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        String gt=this.hienThi.getText();
      if (gt.length()<12){
          if (gt.equals("4")) gt="";
          long so = Long.parseLong(gt+ btn4.getText());
          this.hienThi.setText(String.valueOf(so));
      }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
     String gt=this.hienThi.getText();
      if (gt.length()<12){
          if (gt.equals("2")) gt="";
          long so = Long.parseLong(gt+ btn2.getText());
          this.hienThi.setText(String.valueOf(so));
      }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
       String gt=this.hienThi.getText();
      if (gt.length()<12){
          if (gt.equals("3")) gt="";
          long so = Long.parseLong(gt+ btn3.getText());
          this.hienThi.setText(String.valueOf(so));
      }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        String gt=this.hienThi.getText();
      if (gt.length()<12){
          if (gt.equals("5")) gt="";
          long so = Long.parseLong(gt+ btn5.getText());
          this.hienThi.setText(String.valueOf(so));
      }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
         String gt=this.hienThi.getText();
      if (gt.length()<12){
          if (gt.equals("6")) gt="";
          long so = Long.parseLong(gt+ btn6.getText());
          this.hienThi.setText(String.valueOf(so));
      }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
         String gt=this.hienThi.getText();
      if (gt.length()<12){
          if (gt.equals("7")) gt="";
          long so = Long.parseLong(gt+ btn7.getText());
          this.hienThi.setText(String.valueOf(so));
      }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
         String gt=this.hienThi.getText();
      if (gt.length()<12){
          if (gt.equals("8")) gt="";
          long so = Long.parseLong(gt+ btn8.getText());
          this.hienThi.setText(String.valueOf(so));
      }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
         String gt=this.hienThi.getText();
      if (gt.length()<12){
          if (gt.equals("9")) gt="";
          long so = Long.parseLong(gt+ btn9.getText());
          this.hienThi.setText(String.valueOf(so));
      }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
         String gt=this.hienThi.getText();
      if (gt.length()<12){
          if (gt.equals("0")) gt="";
          long so = Long.parseLong(gt+ btn0.getText());
          this.hienThi.setText(String.valueOf(so));
      }
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhanActionPerformed
        this.a =Long.parseLong(this.hienThi.getText());
        this.phepToan = "*";this.hienThi.setText("0");
    }//GEN-LAST:event_btnnhanActionPerformed

    private void btntruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntruActionPerformed
       this.a =Long.parseLong(this.hienThi.getText());
        this.phepToan = "-";this.hienThi.setText("0");
    }//GEN-LAST:event_btntruActionPerformed

    private void btncongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncongActionPerformed
       this.a =Long.parseLong(this.hienThi.getText());
        this.phepToan = "+";this.hienThi.setText("0");
    }//GEN-LAST:event_btncongActionPerformed

    private void btnbangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbangActionPerformed
       if(this.phepToan.length()>0){
        long b=Long.parseLong(this.hienThi.getText());
        if(this.phepToan.equals("+"))
        {
            long kq =this.a +b;
            this.hienThi.setText(String.valueOf(kq));
        }
        else if(this.phepToan.equals("-"))
        {
            long kq  =this.a - b;
            this.hienThi.setText(String.valueOf(kq));
        }
        else if(this.phepToan.equals("*"))
        {
            long kq  =this.a * b;
            this.hienThi.setText(String.valueOf(kq));
        }
        else if(this.phepToan.equals("/"))
        {
            long kq  =this.a / b;
            this.hienThi.setText(String.valueOf(kq));
        }
        else if(this.phepToan.equals("Sqrt()"))
        {
                long kq = (long) Math.sqrt(this.a);
                 this.hienThi.setText(String.valueOf(kq));
         } else if(this.phepToan.equals("%"))
         {
                long kq =this.a%b;
                 this.hienThi.setText(String.valueOf(kq));
         } 
         else if(this.phepToan.equals("1/x"))
         {
                long kq =1/this.a;
                 this.hienThi.setText(String.valueOf(kq));
         }else if(this.phepToan.equals("+/-"))
         {
                long kq =-this.a;
                 this.hienThi.setText(String.valueOf(kq));
         }
        this.phepToan = "";this.a=0;
    }
    }//GEN-LAST:event_btnbangActionPerformed

    private void btncanbacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncanbacActionPerformed
       this.a = Long.parseLong(this.hienThi.getText());
                this.phepToan = "Sqrt()";
                this.hienThi.setText("0");
    }//GEN-LAST:event_btncanbacActionPerformed

    private void btnphantramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphantramActionPerformed
        this.a = Long.parseLong(this.hienThi.getText());
                this.phepToan = "%";
                this.hienThi.setText("0");
    }//GEN-LAST:event_btnphantramActionPerformed

    private void btnchiaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchiaxActionPerformed
       this.a = Long.parseLong(this.hienThi.getText());
                this.phepToan = "1/x";
                this.hienThi.setText("0");
    }//GEN-LAST:event_btnchiaxActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        hienThi.setText("");
    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lab2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lab2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lab2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lab2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lab2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnbang;
    private javax.swing.JButton btncanbac;
    private javax.swing.JButton btnchia;
    private javax.swing.JButton btnchiax;
    private javax.swing.JButton btncong;
    private javax.swing.JButton btncongtru;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnnhan;
    private javax.swing.JButton btnphantram;
    private javax.swing.JButton btntru;
    private javax.swing.JTextField hienThi;
    private javax.swing.JButton jButton12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
